/* Generated by Forge compiler — C backend */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdarg.h>
#include "forge_runtime.h"

typedef struct Pos Pos;
typedef struct Span Span;
typedef struct TupleField TupleField;
typedef struct TypeParam TypeParam;
typedef struct Field Field;
typedef struct EnumVariant EnumVariant;
typedef struct InterfaceFieldDecl InterfaceFieldDecl;
typedef struct InterfaceEmbed InterfaceEmbed;
typedef struct DocBlock DocBlock;
typedef struct InvariantDecl InvariantDecl;
typedef struct ImportDecl ImportDecl;
typedef struct RelationSide RelationSide;
typedef struct Comment Comment;
typedef struct StructLitField StructLitField;
typedef struct MapEntry MapEntry;
typedef struct ElseIf ElseIf;
typedef struct SelectCase SelectCase;
typedef struct TypeExpr TypeExpr;
typedef struct Param Param;
typedef struct WhereClause WhereClause;
typedef struct Annotations Annotations;
typedef struct Expr Expr;
typedef struct Pattern Pattern;
typedef struct MatchArm MatchArm;
typedef struct Stmt Stmt;
typedef struct Block Block;
typedef struct DestructorBlock DestructorBlock;
typedef struct FuncDecl FuncDecl;
typedef struct ClassDecl ClassDecl;
typedef struct StructDecl StructDecl;
typedef struct EnumDecl EnumDecl;
typedef struct InterfaceDecl InterfaceDecl;
typedef struct ImplMapping ImplMapping;
typedef struct ImplBlock ImplBlock;
typedef struct RelationDecl RelationDecl;
typedef struct TypeAliasDecl TypeAliasDecl;
typedef struct ForgeBlock ForgeBlock;
typedef struct ForgeFile ForgeFile;
typedef struct UnaryOp UnaryOp;
typedef struct BinaryOp BinaryOp;
typedef struct ImplMappingKind ImplMappingKind;
typedef struct RelationKind RelationKind;
typedef struct TypeExprKind TypeExprKind;
typedef struct ExprKind ExprKind;
typedef struct PatternKind PatternKind;
typedef struct StmtKind StmtKind;

FORGE_SLICE_DEF(MatchArm*, ForgeSlice_MatchArmptr)
FORGE_SLICE_DEF(Pattern*, ForgeSlice_Patternptr)
FORGE_SLICE_DEF(const char*, ForgeSlice_const_charptr)
FORGE_SLICE_DEF(TypeExpr*, ForgeSlice_TypeExprptr)
FORGE_SLICE_DEF(Expr*, ForgeSlice_Exprptr)
FORGE_SLICE_DEF(MapEntry, ForgeSlice_MapEntry)
FORGE_SLICE_DEF(Param*, ForgeSlice_Paramptr)
FORGE_SLICE_DEF(ElseIf, ForgeSlice_ElseIf)
FORGE_SLICE_DEF(SelectCase, ForgeSlice_SelectCase)
FORGE_SLICE_DEF(TupleField, ForgeSlice_TupleField)
FORGE_SLICE_DEF(StructLitField, ForgeSlice_StructLitField)

enum UnaryOp_Tag {
    UnaryOp_Neg = 0,
    UnaryOp_Not = 1
};

struct UnaryOp {
    enum UnaryOp_Tag tag;
    union {
    } data;
};

enum BinaryOp_Tag {
    BinaryOp_Add = 0,
    BinaryOp_Sub = 1,
    BinaryOp_Mul = 2,
    BinaryOp_Div = 3,
    BinaryOp_Mod = 4,
    BinaryOp_Eq = 5,
    BinaryOp_Neq = 6,
    BinaryOp_Lt = 7,
    BinaryOp_Le = 8,
    BinaryOp_Gt = 9,
    BinaryOp_Ge = 10,
    BinaryOp_And = 11,
    BinaryOp_Or = 12,
    BinaryOp_BitAnd = 13,
    BinaryOp_BitOr = 14,
    BinaryOp_BitXor = 15,
    BinaryOp_Shl = 16,
    BinaryOp_Shr = 17
};

struct BinaryOp {
    enum BinaryOp_Tag tag;
    union {
    } data;
};

enum ImplMappingKind_Tag {
    ImplMappingKind_Alias = 0,
    ImplMappingKind_FieldBind = 1,
    ImplMappingKind_Inline = 2
};

struct ImplMappingKind {
    enum ImplMappingKind_Tag tag;
    union {
    } data;
};

enum RelationKind_Tag {
    RelationKind_Owns = 0,
    RelationKind_Refs = 1
};

struct RelationKind {
    enum RelationKind_Tag tag;
    union {
    } data;
};

enum TypeExprKind_Tag {
    TypeExprKind_Named = 0,
    TypeExprKind_Optional = 1,
    TypeExprKind_Union = 2,
    TypeExprKind_Sequence = 3,
    TypeExprKind_Map = 4,
    TypeExprKind_Tuple = 5,
    TypeExprKind_Func = 6,
    TypeExprKind_Channel = 7,
    TypeExprKind_Generator = 8,
    TypeExprKind_Lock = 9,
    TypeExprKind_Unit = 10
};

typedef struct {
    const char* name;
    ForgeSlice_TypeExprptr args;
} TypeExprKind_Named_Data;

typedef struct {
    TypeExpr* inner;
} TypeExprKind_Optional_Data;

typedef struct {
    ForgeSlice_TypeExprptr variants;
} TypeExprKind_Union_Data;

typedef struct {
    TypeExpr* elem;
} TypeExprKind_Sequence_Data;

typedef struct {
    TypeExpr* key;
    TypeExpr* value;
} TypeExprKind_Map_Data;

typedef struct {
    ForgeSlice_TupleField fields;
} TypeExprKind_Tuple_Data;

typedef struct {
    ForgeSlice_TypeExprptr params;
    TypeExpr* ret;
} TypeExprKind_Func_Data;

typedef struct {
    TypeExpr* elem;
} TypeExprKind_Channel_Data;

typedef struct {
    TypeExpr* elem;
} TypeExprKind_Generator_Data;

struct TypeExprKind {
    enum TypeExprKind_Tag tag;
    union {
        TypeExprKind_Named_Data named;
        TypeExprKind_Optional_Data optional;
        TypeExprKind_Union_Data union_;
        TypeExprKind_Sequence_Data sequence;
        TypeExprKind_Map_Data map;
        TypeExprKind_Tuple_Data tuple;
        TypeExprKind_Func_Data func;
        TypeExprKind_Channel_Data channel;
        TypeExprKind_Generator_Data generator;
    } data;
};

enum ExprKind_Tag {
    ExprKind_Ident = 0,
    ExprKind_IntLit = 1,
    ExprKind_FloatLit = 2,
    ExprKind_StringLit = 3,
    ExprKind_StringInterp = 4,
    ExprKind_BoolLit = 5,
    ExprKind_Nil = 6,
    ExprKind_Call = 7,
    ExprKind_MethodCall = 8,
    ExprKind_FieldAccess = 9,
    ExprKind_Index = 10,
    ExprKind_Slice = 11,
    ExprKind_Unary = 12,
    ExprKind_Binary = 13,
    ExprKind_TupleLit = 14,
    ExprKind_ListLit = 15,
    ExprKind_MapLit = 16,
    ExprKind_StructLit = 17,
    ExprKind_Lambda = 18,
    ExprKind_MatchExpr = 19,
    ExprKind_Cast = 20,
    ExprKind_Unwrap = 21,
    ExprKind_Try = 22
};

typedef struct {
    const char* name;
} ExprKind_Ident_Data;

typedef struct {
    const char* value;
    const char* type_hint;
} ExprKind_IntLit_Data;

typedef struct {
    const char* value;
} ExprKind_FloatLit_Data;

typedef struct {
    const char* value;
} ExprKind_StringLit_Data;

typedef struct {
    ForgeSlice_Exprptr parts;
} ExprKind_StringInterp_Data;

typedef struct {
    bool value;
} ExprKind_BoolLit_Data;

typedef struct {
    Expr* func_expr;
    ForgeSlice_TypeExprptr type_args;
    ForgeSlice_Exprptr args;
} ExprKind_Call_Data;

typedef struct {
    Expr* receiver;
    const char* method;
    ForgeSlice_TypeExprptr type_args;
    ForgeSlice_Exprptr args;
} ExprKind_MethodCall_Data;

typedef struct {
    Expr* receiver;
    const char* member;
} ExprKind_FieldAccess_Data;

typedef struct {
    Expr* receiver;
    Expr* index;
} ExprKind_Index_Data;

typedef struct {
    Expr* receiver;
    Expr* low;
    Expr* high;
} ExprKind_Slice_Data;

typedef struct {
    UnaryOp op;
    Expr* operand;
} ExprKind_Unary_Data;

typedef struct {
    Expr* left;
    BinaryOp op;
    Expr* right;
} ExprKind_Binary_Data;

typedef struct {
    ForgeSlice_Exprptr elems;
} ExprKind_TupleLit_Data;

typedef struct {
    ForgeSlice_Exprptr elems;
} ExprKind_ListLit_Data;

typedef struct {
    ForgeSlice_MapEntry entries;
} ExprKind_MapLit_Data;

typedef struct {
    const char* type_name;
    ForgeSlice_StructLitField fields;
} ExprKind_StructLit_Data;

typedef struct {
    ForgeSlice_Paramptr params;
    TypeExpr* return_type;
    Block* body;
} ExprKind_Lambda_Data;

typedef struct {
    Expr* value;
    ForgeSlice_MatchArmptr arms;
} ExprKind_MatchExpr_Data;

typedef struct {
    TypeExpr* target_type;
    Expr* operand;
} ExprKind_Cast_Data;

typedef struct {
    Expr* operand;
} ExprKind_Unwrap_Data;

typedef struct {
    Expr* operand;
} ExprKind_Try_Data;

struct ExprKind {
    enum ExprKind_Tag tag;
    union {
        ExprKind_Ident_Data ident;
        ExprKind_IntLit_Data intlit;
        ExprKind_FloatLit_Data floatlit;
        ExprKind_StringLit_Data stringlit;
        ExprKind_StringInterp_Data stringinterp;
        ExprKind_BoolLit_Data boollit;
        ExprKind_Call_Data call;
        ExprKind_MethodCall_Data methodcall;
        ExprKind_FieldAccess_Data fieldaccess;
        ExprKind_Index_Data index;
        ExprKind_Slice_Data slice;
        ExprKind_Unary_Data unary;
        ExprKind_Binary_Data binary;
        ExprKind_TupleLit_Data tuplelit;
        ExprKind_ListLit_Data listlit;
        ExprKind_MapLit_Data maplit;
        ExprKind_StructLit_Data structlit;
        ExprKind_Lambda_Data lambda;
        ExprKind_MatchExpr_Data matchexpr;
        ExprKind_Cast_Data cast;
        ExprKind_Unwrap_Data unwrap;
        ExprKind_Try_Data try;
    } data;
};

enum PatternKind_Tag {
    PatternKind_Ident = 0,
    PatternKind_Literal = 1,
    PatternKind_Variant = 2,
    PatternKind_Wildcard = 3,
    PatternKind_Tuple = 4
};

typedef struct {
    const char* name;
} PatternKind_Ident_Data;

typedef struct {
    Expr* expr;
} PatternKind_Literal_Data;

typedef struct {
    const char* name;
    ForgeSlice_Patternptr bindings;
} PatternKind_Variant_Data;

typedef struct {
    ForgeSlice_Patternptr elems;
} PatternKind_Tuple_Data;

struct PatternKind {
    enum PatternKind_Tag tag;
    union {
        PatternKind_Ident_Data ident;
        PatternKind_Literal_Data literal;
        PatternKind_Variant_Data variant;
        PatternKind_Tuple_Data tuple;
    } data;
};

enum StmtKind_Tag {
    StmtKind_VarDecl = 0,
    StmtKind_Assign = 1,
    StmtKind_Return = 2,
    StmtKind_ExprStmt = 3,
    StmtKind_If = 4,
    StmtKind_For = 5,
    StmtKind_While = 6,
    StmtKind_Match = 7,
    StmtKind_BlockStmt = 8,
    StmtKind_Cascade = 9,
    StmtKind_Break = 10,
    StmtKind_Continue = 11,
    StmtKind_Spawn = 12,
    StmtKind_Select = 13,
    StmtKind_Yield = 14,
    StmtKind_Lock = 15
};

typedef struct {
    const char* name;
    ForgeSlice_const_charptr names;
    TypeExpr* type_expr;
    bool is_mut;
    Expr* value;
} StmtKind_VarDecl_Data;

typedef struct {
    Expr* target;
    Expr* value;
} StmtKind_Assign_Data;

typedef struct {
    Expr* value;
} StmtKind_Return_Data;

typedef struct {
    Expr* expr;
} StmtKind_ExprStmt_Data;

typedef struct {
    Expr* condition;
    Block* then_block;
    ForgeSlice_ElseIf else_ifs;
    Block* else_block;
} StmtKind_If_Data;

typedef struct {
    const char* var_name;
    const char* index_var;
    Expr* collection;
    Block* body;
} StmtKind_For_Data;

typedef struct {
    Expr* condition;
    Block* body;
} StmtKind_While_Data;

typedef struct {
    Expr* value;
    ForgeSlice_MatchArmptr arms;
} StmtKind_Match_Data;

typedef struct {
    Block* body;
} StmtKind_BlockStmt_Data;

typedef struct {
    Block* body;
} StmtKind_Cascade_Data;

typedef struct {
    Block* body;
} StmtKind_Spawn_Data;

typedef struct {
    ForgeSlice_SelectCase cases;
} StmtKind_Select_Data;

typedef struct {
    Expr* value;
} StmtKind_Yield_Data;

typedef struct {
    Expr* mutex;
    Block* body;
} StmtKind_Lock_Data;

struct StmtKind {
    enum StmtKind_Tag tag;
    union {
        StmtKind_VarDecl_Data vardecl;
        StmtKind_Assign_Data assign;
        StmtKind_Return_Data return_;
        StmtKind_ExprStmt_Data exprstmt;
        StmtKind_If_Data if_;
        StmtKind_For_Data for_;
        StmtKind_While_Data while_;
        StmtKind_Match_Data match;
        StmtKind_BlockStmt_Data blockstmt;
        StmtKind_Cascade_Data cascade;
        StmtKind_Spawn_Data spawn;
        StmtKind_Select_Data select;
        StmtKind_Yield_Data yield;
        StmtKind_Lock_Data lock;
    } data;
};

struct Pos {
    const char* file;
    int32_t line;
    int32_t column;
};

struct Span {
    Pos start;
    Pos end;
};

struct TupleField {
    const char* name;
    TypeExpr* type_expr;
    Span span;
};

struct TypeParam {
    const char* name;
    const char* constraint;
    Span span;
};

struct Field {
    const char* name;
    TypeExpr* type_expr;
    const char* guarded_by;
    const char* why;
    Span span;
};

struct EnumVariant {
    const char* name;
    ForgeSlice_TupleField fields;
    Span span;
};

struct InterfaceFieldDecl {
    const char* type_param;
    const char* name;
    TypeExpr* type_expr;
    Span span;
};

struct InterfaceEmbed {
    const char* name;
    ForgeSlice_TypeExprptr type_args;
    Span span;
};

struct DocBlock {
    const char* section;
    const char* content;
    Span span;
};

struct InvariantDecl {
    const char* claim;
    const char* verified_at;
    Span span;
};

struct ImportDecl {
    const char* alias;
    const char* path;
    Span span;
};

struct RelationSide {
    const char* type_name;
    const char* label;
};

struct Comment {
    const char* text;
    Pos pos;
};

struct StructLitField {
    const char* name;
    Expr* value;
    Span span;
};

struct MapEntry {
    Expr* key;
    Expr* value;
};

struct ElseIf {
    Expr* condition;
    Block* body;
    Span span;
};

struct SelectCase {
    bool is_default;
    const char* bind_var;
    Expr* expr;
    Block* body;
    Span span;
};

struct TypeExpr {
    int _empty;
};

struct Param {
    int _empty;
};

struct WhereClause {
    int _empty;
};

struct Annotations {
    int _empty;
};

struct Expr {
    int _empty;
};

struct Pattern {
    int _empty;
};

struct MatchArm {
    int _empty;
};

struct Stmt {
    int _empty;
};

struct Block {
    int _empty;
};

struct DestructorBlock {
    int _empty;
};

struct FuncDecl {
    int _empty;
};

struct ClassDecl {
    int _empty;
};

struct StructDecl {
    int _empty;
};

struct EnumDecl {
    int _empty;
};

struct InterfaceDecl {
    int _empty;
};

struct ImplMapping {
    int _empty;
};

struct ImplBlock {
    int _empty;
};

struct RelationDecl {
    int _empty;
};

struct TypeAliasDecl {
    int _empty;
};

struct ForgeBlock {
    int _empty;
};

struct ForgeFile {
    int _empty;
};


