package lir

import (
	"fmt"
	"strings"
)

// EmitC generates C source code from a monomorphized LIR program.
// The program MUST be monomorphized before calling this — C has no generics.
func EmitC(prog *LProgram) string {
	g := &cGen{
		prog:       prog,
		indent:     0,
		tempUsed:   map[int]bool{},
		sliceTypes: map[string]string{},
	}
	return g.generate()
}

type cGen struct {
	prog       *LProgram
	buf        strings.Builder
	indent     int
	tempUsed   map[int]bool
	sliceTypes map[string]string // cType(elem) → typedef name
	sliceCount int
}

// ---------------------------------------------------------------------------
// Top-level generation
// ---------------------------------------------------------------------------

func (g *cGen) generate() string {
	g.line("/* Generated by Grok compiler — C backend */")
	g.line("#include <stdio.h>")
	g.line("#include <stdlib.h>")
	g.line("#include <stdint.h>")
	g.line("#include <stdbool.h>")
	g.line("#include <string.h>")
	g.line("")

	// Pre-scan to collect all slice types used in the program
	g.collectSliceTypes()
	// Emit slice type typedefs
	for elemType, name := range g.sliceTypes {
		g.linef("typedef struct { %s* data; int32_t len; int32_t cap; } %s;", elemType, name)
	}
	if len(g.sliceTypes) > 0 {
		g.line("")
	}

	// Forward-declare structs, classes, and enums
	for _, s := range g.prog.Structs {
		g.linef("typedef struct %s %s;", g.structName(s.Name, s.IsExported), g.structName(s.Name, s.IsExported))
	}
	for _, c := range g.prog.Classes {
		g.linef("typedef struct %s %s;", g.structName(c.Name, c.IsExported), g.structName(c.Name, c.IsExported))
	}
	for _, e := range g.prog.Enums {
		g.linef("typedef struct %s %s;", g.structName(e.Name, e.IsExported), g.structName(e.Name, e.IsExported))
	}
	if len(g.prog.Structs)+len(g.prog.Classes)+len(g.prog.Enums) > 0 {
		g.line("")
	}

	// Emit struct definitions
	for _, s := range g.prog.Structs {
		g.emitStructDecl(&s)
	}

	// Emit class definitions (heap-allocated structs)
	for _, c := range g.prog.Classes {
		g.emitClassDecl(&c)
	}

	// Emit enum definitions (tagged unions)
	for _, e := range g.prog.Enums {
		g.emitEnumDecl(&e)
	}

	// Emit type aliases
	for _, td := range g.prog.TypeDefs {
		g.linef("typedef %s %s;", g.cType(td.Type), g.visName(td.Name, td.IsExported))
		g.line("")
	}

	// Forward-declare all functions
	for _, f := range g.prog.Functions {
		if f.Name == "main" {
			continue // main has special signature
		}
		g.emitFuncForwardDecl(&f)
	}
	if len(g.prog.Functions) > 0 {
		g.line("")
	}

	// Emit function bodies
	for _, f := range g.prog.Functions {
		g.emitFuncDecl(&f)
	}

	return g.buf.String()
}

// ---------------------------------------------------------------------------
// Type declarations
// ---------------------------------------------------------------------------

func (g *cGen) emitStructDecl(s *LStructDecl) {
	name := g.structName(s.Name, s.IsExported)
	g.linef("struct %s {", name)
	g.indent++
	for _, f := range s.Fields {
		g.linef("%s;", g.cFieldDecl(f.Type, f.Name))
	}
	g.indent--
	g.line("};")
	g.line("")
}

func (g *cGen) emitClassDecl(c *LClassDecl) {
	name := g.structName(c.Name, c.IsExported)
	g.linef("struct %s {", name)
	g.indent++
	for _, f := range c.Fields {
		g.linef("%s;", g.cFieldDecl(f.Type, f.Name))
	}
	g.indent--
	g.line("};")
	g.line("")
}

func (g *cGen) emitEnumDecl(e *LEnumDecl) {
	name := g.structName(e.Name, e.IsExported)
	// Emit tag enum
	g.linef("enum %s_Tag {", name)
	g.indent++
	for i, v := range e.Variants {
		comma := ","
		if i == len(e.Variants)-1 {
			comma = ""
		}
		g.linef("%s_%s = %d%s", name, v.Name, v.Tag, comma)
	}
	g.indent--
	g.line("};")
	g.line("")

	// Emit variant data structs
	for _, v := range e.Variants {
		if len(v.Fields) > 0 {
			g.linef("typedef struct {")
			g.indent++
			for _, f := range v.Fields {
				g.linef("%s;", g.cFieldDecl(f.Type, f.Name))
			}
			g.indent--
			g.linef("} %s_%s_Data;", name, v.Name)
			g.line("")
		}
	}

	// Emit the tagged union
	g.linef("struct %s {", name)
	g.indent++
	g.linef("enum %s_Tag tag;", name)
	g.line("union {")
	g.indent++
	for _, v := range e.Variants {
		if len(v.Fields) > 0 {
			g.linef("%s_%s_Data %s;", name, v.Name, strings.ToLower(v.Name))
		}
	}
	g.indent--
	g.line("} data;")
	g.indent--
	g.line("};")
	g.line("")
}

// ---------------------------------------------------------------------------
// Function declarations
// ---------------------------------------------------------------------------

func (g *cGen) emitFuncForwardDecl(f *LFuncDecl) {
	name := g.funcName(f)
	if name == "main" {
		return // main doesn't need a forward declaration
	}
	retType := g.cReturnType(f.ReturnType)
	params := g.cParamList(f)
	g.linef("%s %s(%s);", retType, name, params)
}

func (g *cGen) emitFuncDecl(f *LFuncDecl) {
	retType := g.cReturnType(f.ReturnType)
	params := g.cParamList(f)
	name := g.funcName(f)

	if name == "main" {
		// C main returns int
		g.linef("int main(void) {")
	} else {
		g.linef("%s %s(%s) {", retType, name, params)
	}
	g.indent++
	g.emitStmts(f.Body)
	if name == "main" {
		g.line("return 0;")
	}
	g.indent--
	g.line("}")
	g.line("")
}

func (g *cGen) funcName(f *LFuncDecl) string {
	if f.Receiver != "" {
		return f.Receiver + "_" + f.Name
	}
	// In C, exported "Main" is the entry point "main"
	if f.Name == "Main" {
		return "main"
	}
	return f.Name
}

func (g *cGen) cParamList(f *LFuncDecl) string {
	var parts []string
	for _, p := range f.Params {
		parts = append(parts, g.cFieldDecl(p.Type, p.Name))
	}
	if len(parts) == 0 {
		return "void"
	}
	return strings.Join(parts, ", ")
}

func (g *cGen) cReturnType(t *LType) string {
	if t == nil {
		return "void"
	}
	return g.cType(t)
}

// ---------------------------------------------------------------------------
// Statement emission
// ---------------------------------------------------------------------------

func (g *cGen) emitStmts(stmts []LStmt) {
	for i := range stmts {
		g.emitStmt(&stmts[i])
	}
}

func (g *cGen) emitStmt(s *LStmt) {
	switch s.Kind {
	case LStmtTempDef:
		d := s.Data.(*LTempDef)
		ty := g.exprType(&d.Expr)
		g.linef("%s _t%d = %s;", g.cType(ty), d.ID, g.emitExprStr(&d.Expr))

	case LStmtVarDecl:
		d := s.Data.(*LVarDecl)
		if d.Name == "_" {
			// Discard variable — just evaluate the init for side effects
			if d.Init != nil {
				g.linef("(void)%s;", g.emitValue(d.Init))
			}
			return
		}
		if d.Init != nil {
			g.linef("%s %s = %s;", g.cType(d.Type), d.Name, g.emitValue(d.Init))
		} else {
			g.linef("%s %s = %s;", g.cType(d.Type), d.Name, g.zeroValue(d.Type))
		}

	case LStmtAssign:
		d := s.Data.(*LAssign)
		g.linef("%s = %s;", d.Target, g.emitValue(&d.Value))

	case LStmtStructSet:
		d := s.Data.(*LStructSet)
		g.linef("%s.%s = %s;", g.emitValue(&d.Receiver), d.Field, g.emitValue(&d.Value))

	case LStmtClassSet:
		d := s.Data.(*LClassSet)
		g.linef("%s->%s = %s;", g.emitValue(&d.Handle), d.Field, g.emitValue(&d.Value))

	case LStmtIndexSet:
		d := s.Data.(*LIndexSet)
		// For now, assume array-like indexing
		g.linef("%s.data[%s] = %s;", g.emitValue(&d.Collection), g.emitValue(&d.Index), g.emitValue(&d.Value))

	case LStmtReturn:
		d := s.Data.(*LReturn)
		if len(d.Values) == 0 {
			g.line("return;")
		} else if len(d.Values) == 1 {
			g.linef("return %s;", g.emitValue(&d.Values[0]))
		} else {
			// Multiple returns need a result struct (TODO)
			g.linef("return %s;", g.emitValue(&d.Values[0]))
		}

	case LStmtIf:
		d := s.Data.(*LIf)
		g.linef("if (%s) {", g.emitValue(&d.Cond))
		g.indent++
		g.emitStmts(d.Then)
		g.indent--
		if len(d.Else) > 0 {
			g.line("} else {")
			g.indent++
			g.emitStmts(d.Else)
			g.indent--
		}
		g.line("}")

	case LStmtWhile:
		d := s.Data.(*LWhile)
		g.line("while (1) {")
		g.indent++
		g.emitStmts(d.CondBlock)
		g.linef("if (!(%s)) break;", g.emitValue(&d.CondVar))
		g.emitStmts(d.Body)
		g.indent--
		g.line("}")

	case LStmtFor:
		d := s.Data.(*LFor)
		collStr := g.emitValue(&d.Collection)
		if d.IndexVar != "" {
			g.linef("for (int32_t %s = 0; %s < %s.len; %s++) {", d.IndexVar, d.IndexVar, collStr, d.IndexVar)
			g.indent++
			g.linef("%s %s = %s.data[%s];", g.cType(d.VarType), d.Var, collStr, d.IndexVar)
		} else {
			idxVar := "_idx"
			g.linef("for (int32_t %s = 0; %s < %s.len; %s++) {", idxVar, idxVar, collStr, idxVar)
			g.indent++
			g.linef("%s %s = %s.data[%s];", g.cType(d.VarType), d.Var, collStr, idxVar)
		}
		g.emitStmts(d.Body)
		g.indent--
		g.line("}")

	case LStmtSwitch:
		d := s.Data.(*LSwitch)
		g.linef("switch (%s) {", g.emitValue(&d.Tag))
		for _, c := range d.Cases {
			g.linef("case %d: {", c.Tag)
			g.indent++
			if c.Binding != "" && d.EnumName != "" {
				// Extract variant data
				g.linef("/* binding: %s */", c.Binding)
			}
			g.emitStmts(c.Body)
			g.line("break;")
			g.indent--
			g.line("}")
		}
		g.line("}")

	case LStmtTypeSwitch:
		d := s.Data.(*LTypeSwitch)
		// Emit as if-else chain on enum tag
		g.linef("switch (%s.tag) {", g.emitValue(&d.Value))
		for _, c := range d.Cases {
			if c.Type != nil {
				g.linef("case /* %s */: {", g.cType(c.Type))
			} else {
				g.line("default: {")
			}
			g.indent++
			g.emitStmts(c.Body)
			g.line("break;")
			g.indent--
			g.line("}")
		}
		g.line("}")

	case LStmtBlock:
		d := s.Data.(*LBlock)
		g.line("{")
		g.indent++
		g.emitStmts(d.Stmts)
		g.indent--
		g.line("}")

	case LStmtSideEffect:
		d := s.Data.(*LSideEffect)
		g.linef("%s;", g.emitExprStr(&d.Expr))

	case LStmtMultiAssign:
		d := s.Data.(*LMultiAssign)
		// Multi-assign: typically (val, err) = expr
		// Emit as a struct assignment
		exprStr := g.emitExprStr(&d.Expr)
		if len(d.Names) == 2 {
			tmpName := fmt.Sprintf("_multi_%d", g.nextTemp())
			g.linef("typeof(%s) %s = %s;", exprStr, tmpName, exprStr)
			// TODO: proper multi-value handling
		} else {
			g.linef("/* multi-assign: %s = %s */", strings.Join(d.Names, ", "), exprStr)
		}

	case LStmtSend:
		d := s.Data.(*LSend)
		g.linef("/* channel send: %s <- %s */", g.emitValue(&d.Channel), g.emitValue(&d.Value))

	case LStmtSpawn:
		g.line("/* spawn: goroutines not supported in C backend */")

	case LStmtSelect:
		g.line("/* select: channels not supported in C backend */")

	case LStmtDefer:
		d := s.Data.(*LDefer)
		g.line("/* defer (executed inline — no stack unwinding): */")
		g.emitStmts(d.Body)

	case LStmtLock:
		d := s.Data.(*LLock)
		g.line("/* lock: */")
		g.line("{")
		g.indent++
		_ = d.Mutex
		g.emitStmts(d.Body)
		g.indent--
		g.line("}")

	case LStmtExpr:
		d := s.Data.(*LExprStmt)
		g.linef("_t%d;", d.TempID)

	case LStmtBreak:
		g.line("break;")

	case LStmtContinue:
		g.line("continue;")
	}
}

// ---------------------------------------------------------------------------
// Expression emission (returns string)
// ---------------------------------------------------------------------------

func (g *cGen) emitExprStr(e *LExpr) string {
	switch e.Kind {
	case LExprCall:
		d := e.Data.(*LCallData)
		name := d.Func
		// Map known stdlib functions
		if name == "fmt.Println" || name == "Println" || name == "println" {
			return g.emitPrintln(d.Args)
		}
		if name == "fmt.Printf" || name == "Printf" || name == "printf" {
			return g.emitPrintf(d.Args)
		}
		if name == "fmt.Sprintf" || name == "Sprintf" {
			return g.emitSprintf(d.Args)
		}
		args := g.emitArgs(d.Args)
		return fmt.Sprintf("%s(%s)", name, args)

	case LExprMethodCall:
		d := e.Data.(*LMethodCallData)
		recv := g.emitValue(&d.Receiver)
		args := g.emitArgs(d.Args)
		methodName := d.Receiver.Type.Name + "_" + d.Method
		if args != "" {
			return fmt.Sprintf("%s(%s, %s)", methodName, recv, args)
		}
		return fmt.Sprintf("%s(%s)", methodName, recv)

	case LExprClassAlloc:
		d := e.Data.(*LClassAllocData)
		name := g.structName(d.Class, false)
		var fieldInits []string
		for _, f := range d.Fields {
			fieldInits = append(fieldInits, fmt.Sprintf(".%s = %s", f.Name, g.emitValue(&f.Value)))
		}
		return fmt.Sprintf("({ %s* _p = malloc(sizeof(%s)); *_p = (%s){%s}; _p; })",
			name, name, name, strings.Join(fieldInits, ", "))

	case LExprStructLit:
		d := e.Data.(*LStructLitData)
		var fieldInits []string
		for _, f := range d.Fields {
			fieldInits = append(fieldInits, fmt.Sprintf(".%s = %s", f.Name, g.emitValue(&f.Value)))
		}
		typeName := "/* struct */"
		if e.Type != nil {
			typeName = g.cType(e.Type)
		}
		return fmt.Sprintf("(%s){%s}", typeName, strings.Join(fieldInits, ", "))

	case LExprBinOp:
		d := e.Data.(*LBinOpData)
		left := g.emitValue(&d.Left)
		right := g.emitValue(&d.Right)
		// String equality
		if d.Left.Type != nil && d.Left.Type.Kind == LTyString {
			if d.Op == LBinEq {
				return fmt.Sprintf("(strcmp(%s, %s) == 0)", left, right)
			}
			if d.Op == LBinNe {
				return fmt.Sprintf("(strcmp(%s, %s) != 0)", left, right)
			}
		}
		return fmt.Sprintf("(%s %s %s)", left, cBinOp(d.Op), right)

	case LExprUnOp:
		d := e.Data.(*LUnOpData)
		return fmt.Sprintf("(%s%s)", cUnOp(d.Op), g.emitValue(&d.Operand))

	case LExprCast:
		d := e.Data.(*LCastData)
		return fmt.Sprintf("((%s)%s)", g.cType(d.Target), g.emitValue(&d.Operand))

	case LExprBuiltin:
		d := e.Data.(*LBuiltinData)
		return g.emitBuiltin(d)

	case LExprStructField:
		d := e.Data.(*LStructFieldData)
		return fmt.Sprintf("%s.%s", g.emitValue(&d.Receiver), d.Field)

	case LExprClassGet:
		d := e.Data.(*LClassGetData)
		return fmt.Sprintf("%s->%s", g.emitValue(&d.Handle), d.Field)

	case LExprIndexGet:
		d := e.Data.(*LIndexGetData)
		return fmt.Sprintf("%s.data[%s]", g.emitValue(&d.Collection), g.emitValue(&d.Index))

	case LExprSlice:
		d := e.Data.(*LSliceData)
		// Simplified: just reference the collection
		return g.emitValue(&d.Collection)

	case LExprWrapOptional:
		d := e.Data.(*LWrapOptionalData)
		// TODO: proper optional wrapping
		return g.emitValue(&d.Value)

	case LExprUnwrapOptional:
		d := e.Data.(*LUnwrapOptionalData)
		return g.emitValue(&d.Value)

	case LExprIsNull:
		d := e.Data.(*LIsNullData)
		if d.Value.Type != nil && d.Value.Type.Kind == LTyClassHandle {
			return fmt.Sprintf("(%s == NULL)", g.emitValue(&d.Value))
		}
		return fmt.Sprintf("(!%s_has)", g.emitValue(&d.Value))

	case LExprVariantConstruct:
		d := e.Data.(*LVariantConstructData)
		enumName := d.Enum
		if enumName == "" {
			enumName = "Enum"
		}
		structName := g.structName(enumName, false)
		if len(d.Fields) == 0 {
			return fmt.Sprintf("(%s){.tag = %s_%s}", structName, structName, d.Variant)
		}
		var fieldInits []string
		for _, f := range d.Fields {
			fieldInits = append(fieldInits, g.emitValue(&f))
		}
		variantLower := strings.ToLower(d.Variant)
		// Build the variant data init
		dataInit := strings.Join(fieldInits, ", ")
		return fmt.Sprintf("(%s){.tag = %s_%s, .data.%s = {%s}}",
			structName, structName, d.Variant, variantLower, dataInit)

	case LExprVariantTag:
		d := e.Data.(*LVariantTagData)
		return fmt.Sprintf("%s.tag", g.emitValue(&d.Value))

	case LExprVariantData:
		d := e.Data.(*LVariantDataData)
		variantLower := strings.ToLower(d.Variant)
		if d.Field != "" {
			return fmt.Sprintf("%s.data.%s.%s", g.emitValue(&d.Value), variantLower, d.Field)
		}
		return fmt.Sprintf("%s.data.%s", g.emitValue(&d.Value), variantLower)

	case LExprFuncLit:
		return "/* function literal: not supported in C */"

	case LExprFormat:
		d := e.Data.(*LFormatData)
		return g.emitFormat(d)

	case LExprExtractValue:
		d := e.Data.(*LExtractValueData)
		return fmt.Sprintf("%s.value", g.emitValue(&d.Value))

	case LExprExtractError:
		d := e.Data.(*LExtractErrorData)
		return fmt.Sprintf("%s.error", g.emitValue(&d.Value))

	case LExprMakeResult:
		d := e.Data.(*LMakeResultData)
		return fmt.Sprintf("/* make_result(%s, %s) */", g.emitValue(&d.Value), g.emitValue(&d.Err))

	case LExprMakeSlice:
		return "/* make_slice */"

	case LExprMakeMap:
		return "/* make_map */"

	case LExprMakeChannel:
		return "/* make_channel: not supported in C */"

	case LExprFuncRef:
		d := e.Data.(*LFuncRefData)
		return d.Name

	case LExprEnvGet:
		d := e.Data.(*LEnvGetData)
		return fmt.Sprintf("%s.%s", g.emitValue(&d.Env), d.Field)

	default:
		return fmt.Sprintf("/* unknown expr kind %d */", e.Kind)
	}
}

// ---------------------------------------------------------------------------
// Value emission
// ---------------------------------------------------------------------------

func (g *cGen) emitValue(v *LValue) string {
	switch v.Kind {
	case LValVar:
		return v.Name
	case LValTemp:
		return fmt.Sprintf("_t%d", v.TempID)
	case LValGlobal:
		return v.Name
	case LValLitInt:
		return fmt.Sprintf("%d", v.IntVal)
	case LValLitUint:
		return fmt.Sprintf("%dU", v.UintVal)
	case LValLitFloat:
		return fmt.Sprintf("%g", v.FloatVal)
	case LValLitString:
		return fmt.Sprintf("%q", v.StrVal)
	case LValLitBool:
		if v.BoolVal {
			return "true"
		}
		return "false"
	case LValLitNull:
		return "NULL"
	default:
		return "/* unknown value */"
	}
}

// ---------------------------------------------------------------------------
// Builtins
// ---------------------------------------------------------------------------

func (g *cGen) emitBuiltin(d *LBuiltinData) string {
	switch d.Name {
	case "len":
		if len(d.Args) > 0 && d.Args[0].Type != nil && d.Args[0].Type.Kind == LTyString {
			return fmt.Sprintf("((int32_t)strlen(%s))", g.emitValue(&d.Args[0]))
		}
		return fmt.Sprintf("%s.len", g.emitValue(&d.Args[0]))
	case "append", "slice_push":
		if len(d.Args) >= 2 {
			return fmt.Sprintf("/* append(%s, %s) */", g.emitValue(&d.Args[0]), g.emitValue(&d.Args[1]))
		}
		return "/* append */"
	case "has_prefix":
		if len(d.Args) >= 2 {
			return fmt.Sprintf("(strncmp(%s, %s, strlen(%s)) == 0)", g.emitValue(&d.Args[0]), g.emitValue(&d.Args[1]), g.emitValue(&d.Args[1]))
		}
	case "has_suffix":
		if len(d.Args) >= 2 {
			s := g.emitValue(&d.Args[0])
			sfx := g.emitValue(&d.Args[1])
			return fmt.Sprintf("(strlen(%s) >= strlen(%s) && strcmp(%s + strlen(%s) - strlen(%s), %s) == 0)",
				s, sfx, s, s, sfx, sfx)
		}
	case "println", "Println":
		return g.emitPrintln(d.Args)
	}
	// Generic fallback
	var args []string
	for _, a := range d.Args {
		args = append(args, g.emitValue(&a))
	}
	return fmt.Sprintf("/* builtin %s(%s) */", d.Name, strings.Join(args, ", "))
}

func (g *cGen) emitPrintln(args []LValue) string {
	if len(args) == 0 {
		return `printf("\n")`
	}
	var fmtParts []string
	var argParts []string
	for _, a := range args {
		spec := g.printfSpec(&a)
		fmtParts = append(fmtParts, spec)
		if spec != `\n` {
			argParts = append(argParts, g.emitValue(&a))
		}
	}
	fmtStr := strings.Join(fmtParts, " ") + `\n`
	if len(argParts) == 0 {
		return fmt.Sprintf(`printf("%s")`, fmtStr)
	}
	return fmt.Sprintf(`printf("%s", %s)`, fmtStr, strings.Join(argParts, ", "))
}

func (g *cGen) emitPrintf(args []LValue) string {
	if len(args) == 0 {
		return `printf("")`
	}
	// First arg is format string
	rest := make([]string, 0, len(args)-1)
	for _, a := range args[1:] {
		rest = append(rest, g.emitValue(&a))
	}
	if len(rest) == 0 {
		return fmt.Sprintf("printf(%s)", g.emitValue(&args[0]))
	}
	return fmt.Sprintf("printf(%s, %s)", g.emitValue(&args[0]), strings.Join(rest, ", "))
}

func (g *cGen) emitSprintf(args []LValue) string {
	return fmt.Sprintf("/* sprintf not supported yet */")
}

func (g *cGen) emitFormat(d *LFormatData) string {
	// f-string → snprintf or inline
	var fmtParts []string
	var argParts []string
	for _, p := range d.Parts {
		if p.IsLiteral {
			fmtParts = append(fmtParts, escapeC(p.Text))
		} else {
			spec := g.printfSpec(&p.Value)
			fmtParts = append(fmtParts, spec)
			argParts = append(argParts, g.emitValue(&p.Value))
		}
	}
	// Return a static buffer sprintf (simplified)
	fmtStr := strings.Join(fmtParts, "")
	if len(argParts) == 0 {
		return fmt.Sprintf(`"%s"`, fmtStr)
	}
	// Use a GCC statement expression with a static buffer
	return fmt.Sprintf(`({ static char _buf[256]; snprintf(_buf, 256, "%s", %s); _buf; })`,
		fmtStr, strings.Join(argParts, ", "))
}

func (g *cGen) printfSpec(v *LValue) string {
	if v.Type == nil {
		return "%d"
	}
	switch v.Type.Kind {
	case LTyI8, LTyI16, LTyI32, LTyPlatformInt:
		return "%d"
	case LTyI64:
		return "%lld"
	case LTyU8, LTyU16, LTyU32, LTyPlatformUint:
		return "%u"
	case LTyU64:
		return "%llu"
	case LTyF32, LTyF64:
		return "%g"
	case LTyBool:
		return "%s"
	case LTyString:
		return "%s"
	default:
		return "%d"
	}
}

func (g *cGen) emitArgs(args []LValue) string {
	var parts []string
	for _, a := range args {
		parts = append(parts, g.emitValue(&a))
	}
	return strings.Join(parts, ", ")
}

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

func (g *cGen) cType(t *LType) string {
	if t == nil {
		return "void"
	}
	switch t.Kind {
	case LTyI8:
		return "int8_t"
	case LTyI16:
		return "int16_t"
	case LTyI32:
		return "int32_t"
	case LTyI64:
		return "int64_t"
	case LTyU8:
		return "uint8_t"
	case LTyU16:
		return "uint16_t"
	case LTyU32:
		return "uint32_t"
	case LTyU64:
		return "uint64_t"
	case LTyF32:
		return "float"
	case LTyF64:
		return "double"
	case LTyBool:
		return "bool"
	case LTyString:
		return "const char*"
	case LTyPlatformInt:
		return "int"
	case LTyPlatformUint:
		return "unsigned int"
	case LTySlice:
		return g.sliceTypeName(t.Elem)
	case LTyMap:
		return fmt.Sprintf("/* map<%s,%s> */void*", g.cType(t.Key), g.cType(t.Elem))
	case LTyStruct:
		return g.structName(t.Name, t.IsExported)
	case LTyClassHandle:
		return g.structName(t.Name, t.IsExported) + "*"
	case LTyOptional:
		return g.cType(t.Elem) // Simplified: just the inner type
	case LTyTaggedUnion:
		return g.structName(t.Name, t.IsExported)
	case LTyChannel:
		return "/* channel */ void*"
	case LTyFuncPtr:
		// Function pointer
		ret := g.cReturnType(t.Return)
		var params []string
		for _, p := range t.Params {
			params = append(params, g.cType(p))
		}
		if len(params) == 0 {
			return fmt.Sprintf("%s (*)(void)", ret)
		}
		return fmt.Sprintf("%s (*)(%s)", ret, strings.Join(params, ", "))
	case LTyUnit:
		return "void"
	case LTyError:
		return "int /* error */"
	case LTyErrorResult:
		return fmt.Sprintf("struct { %s value; int error; }", g.cType(t.Elem))
	case LTyTuple:
		var fields []string
		for i, f := range t.Fields {
			fields = append(fields, fmt.Sprintf("%s _%d", g.cType(f.Type), i))
		}
		return fmt.Sprintf("struct { %s }", strings.Join(fields, "; "))
	case LTyMutex:
		return "/* mutex */ int"
	case LTyTypeVar:
		return fmt.Sprintf("/* typevar %s */ void*", t.Name)
	case LTyAny:
		return "void*"
	default:
		return fmt.Sprintf("/* unknown type %d */", t.Kind)
	}
}

func (g *cGen) cFieldDecl(t *LType, name string) string {
	// Handle function pointer types which need the name embedded
	if t != nil && t.Kind == LTyFuncPtr {
		ret := g.cReturnType(t.Return)
		var params []string
		for _, p := range t.Params {
			params = append(params, g.cType(p))
		}
		if len(params) == 0 {
			return fmt.Sprintf("%s (*%s)(void)", ret, name)
		}
		return fmt.Sprintf("%s (*%s)(%s)", ret, name, strings.Join(params, ", "))
	}
	return g.cType(t) + " " + name
}

// ---------------------------------------------------------------------------
// Name helpers
// ---------------------------------------------------------------------------

func (g *cGen) structName(name string, exported bool) string {
	return name
}

// sliceTypeName returns a named typedef for a slice of the given element type.
func (g *cGen) sliceTypeName(elem *LType) string {
	key := g.cType(elem)
	if name, ok := g.sliceTypes[key]; ok {
		return name
	}
	g.sliceCount++
	name := fmt.Sprintf("GrokSlice_%s", sanitizeCTypeName(key))
	g.sliceTypes[key] = name
	return name
}

// collectSliceTypes walks all types in the program to pre-register slice types.
func (g *cGen) collectSliceTypes() {
	var walkType func(t *LType)
	walkType = func(t *LType) {
		if t == nil {
			return
		}
		if t.Kind == LTySlice {
			g.sliceTypeName(t.Elem)
		}
		walkType(t.Elem)
		walkType(t.Key)
		walkType(t.Return)
		for _, p := range t.Params {
			walkType(p)
		}
		for _, f := range t.Fields {
			walkType(f.Type)
		}
	}
	for _, f := range g.prog.Functions {
		walkType(f.ReturnType)
		for _, p := range f.Params {
			walkType(p.Type)
		}
	}
	for _, s := range g.prog.Structs {
		for _, f := range s.Fields {
			walkType(f.Type)
		}
	}
	for _, c := range g.prog.Classes {
		for _, f := range c.Fields {
			walkType(f.Type)
		}
	}
}

func sanitizeCTypeName(s string) string {
	r := strings.NewReplacer(" ", "_", "*", "ptr", "[", "", "]", "", "(", "", ")", "", ",", "_")
	return r.Replace(s)
}

func (g *cGen) visName(name string, exported bool) string {
	return name
}

func (g *cGen) zeroValue(t *LType) string {
	if t == nil {
		return "0"
	}
	switch t.Kind {
	case LTyI8, LTyI16, LTyI32, LTyI64, LTyPlatformInt:
		return "0"
	case LTyU8, LTyU16, LTyU32, LTyU64, LTyPlatformUint:
		return "0"
	case LTyF32, LTyF64:
		return "0.0"
	case LTyBool:
		return "false"
	case LTyString:
		return `""`
	case LTyClassHandle:
		return "NULL"
	case LTyStruct, LTyTaggedUnion:
		return "{0}"
	default:
		return "{0}"
	}
}

// ---------------------------------------------------------------------------
// Output helpers
// ---------------------------------------------------------------------------

func (g *cGen) line(s string) {
	g.buf.WriteString(strings.Repeat("    ", g.indent))
	g.buf.WriteString(s)
	g.buf.WriteByte('\n')
}

func (g *cGen) linef(format string, args ...interface{}) {
	g.line(fmt.Sprintf(format, args...))
}

func (g *cGen) exprType(e *LExpr) *LType {
	if e == nil || e.Type == nil {
		return &LType{Kind: LTyI32}
	}
	return e.Type
}

func (g *cGen) nextTemp() int {
	id := len(g.tempUsed) + 9000
	g.tempUsed[id] = true
	return id
}

func escapeC(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\t", "\\t")
	return s
}

func cBinOp(op LBinOpKind) string {
	switch op {
	case LBinAdd:
		return "+"
	case LBinSub:
		return "-"
	case LBinMul:
		return "*"
	case LBinDiv:
		return "/"
	case LBinMod:
		return "%"
	case LBinEq:
		return "=="
	case LBinNe:
		return "!="
	case LBinLt:
		return "<"
	case LBinLe:
		return "<="
	case LBinGt:
		return ">"
	case LBinGe:
		return ">="
	case LBinAnd:
		return "&&"
	case LBinOr:
		return "||"
	case LBinBitAnd:
		return "&"
	case LBinBitOr:
		return "|"
	case LBinBitXor:
		return "^"
	case LBinShl:
		return "<<"
	case LBinShr:
		return ">>"
	default:
		return "?"
	}
}

func cUnOp(op LUnOpKind) string {
	switch op {
	case LUnNeg:
		return "-"
	case LUnNot:
		return "!"
	case LUnBitNot:
		return "~"
	default:
		return "?"
	}
}
